// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkF0BOpu7bqroopfvXgVOpodolhTbdlyU',
    appId: '1:193177924435:web:c6a87ecc782cb59616e7a6',
    messagingSenderId: '193177924435',
    projectId: 'facebook-app-9fb0d',
    authDomain: 'facebook-app-9fb0d.firebaseapp.com',
    storageBucket: 'facebook-app-9fb0d.appspot.com',
    measurementId: 'G-4180YE790Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv79CIE2KXvsbLes-aJKt4NxXgiJqFOdU',
    appId: '1:193177924435:android:56372b46d7a081b416e7a6',
    messagingSenderId: '193177924435',
    projectId: 'facebook-app-9fb0d',
    storageBucket: 'facebook-app-9fb0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIRzHWFWpID2WqsuVwyUMiu3PpiVdAhAo',
    appId: '1:193177924435:ios:cb2a483e06df3bee16e7a6',
    messagingSenderId: '193177924435',
    projectId: 'facebook-app-9fb0d',
    storageBucket: 'facebook-app-9fb0d.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIRzHWFWpID2WqsuVwyUMiu3PpiVdAhAo',
    appId: '1:193177924435:ios:cb2a483e06df3bee16e7a6',
    messagingSenderId: '193177924435',
    projectId: 'facebook-app-9fb0d',
    storageBucket: 'facebook-app-9fb0d.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkF0BOpu7bqroopfvXgVOpodolhTbdlyU',
    appId: '1:193177924435:web:c87f714347b6312c16e7a6',
    messagingSenderId: '193177924435',
    projectId: 'facebook-app-9fb0d',
    authDomain: 'facebook-app-9fb0d.firebaseapp.com',
    storageBucket: 'facebook-app-9fb0d.appspot.com',
    measurementId: 'G-KCBH6ZSGR2',
  );

}